name: 'Build and test icepack2'
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: docker.io/firedrakeproject/firedrake-vanilla:2023-10
      options: --user root
    steps:
      - name: Install patchelf
        run: |
          apt update
          apt install -yq patchelf
      - name: Check out git repository
        uses: actions/checkout@v3
      - name: Activate Firedrake virtual environment
        run: |
          . /home/firedrake/firedrake/bin/activate
          echo PATH=$PATH >> $GITHUB_ENV
      - name: Install package
        run: pip install --editable .
      - name: Run unit tests
        run: pytest -s --verbose
